CREATE TABLE IF NOT EXISTS PROJECT_ACCESS_ENVIRONMENT
(
    ID                BIGINT AUTO_INCREMENT PRIMARY KEY,
    GMT_CREATE        TIMESTAMP,
    GMT_MODIFIED      TIMESTAMP,
    PROJECT_ACCESS_ID BIGINT NOT NULL,
    ENVIRONMENT_ID    BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_PROJECT_ACCESS_ENVIRONMENT_ACCESS
    ON PROJECT_ACCESS_ENVIRONMENT (PROJECT_ACCESS_ID);

CREATE UNIQUE INDEX IF NOT EXISTS UK_PROJECT_ACCESS_ENVIRONMENT
    ON PROJECT_ACCESS_ENVIRONMENT (PROJECT_ACCESS_ID, ENVIRONMENT_ID);
